### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by zickgraf**
See commit messages for details.

Note: I have not tested the commits extensively.

### CODE REVIEW

**Review by mohamed-barakat — COMMENTED** [review]
I do not understand why you disable the check (in the underlying category) for an evaluated cell.

**Review by mohamed-barakat — COMMENTED** [review]
Did you test this change? I do not remember the details but I remember that I had to check several corner cases to get this code right.

**Comment by zickgraf** [comment]
> I do not understand why you disable the check (in the underlying category) for an evaluated cell.

I assume you are referring  to the commit "Fix IsIdenticalToIdentity/ZeroMorphism"?

From the CAP documentation for `IsIdenticalToIdentityMorphism`:
> The argument is a morphism α : a → b. The output is true if α = id_a , otherwise the output is
false.

I think the equality sign should be interpreted as `IsEqualForMorphisms`. Then, in our context a morphism which does not have a genesis can never be equal (w.r.t. `IsEqualForMorphisms`)  to the identity morphism because the latter one has a genesis.

**Comment by mohamed-barakat** [comment]
I am primarily thinking of the primitive morphisms which are initially given. I want to treat them with the logic of the underlying category. I only allow operations that do not trigger evaluations.

**Pull request closed without merging**
